# Generated by Django 4.0.4 on 2022-09-16 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('limousineapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='testimonial',
            new_name='reviews',
        ),
    ]
