# Generated by Django 4.0.4 on 2022-09-16 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('limousineapp', '0002_rename_testimonial_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reviews',
        ),
    ]
